# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "addressabler"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Flip Sasser"]
  s.date = "2013-03-25"
  s.description = "\n    Addressabler extends the Addressable::URI class to provide information about, and manipulation of, specific parts of URI strings. It adds a `tld' method, a `domain' method,\n    and a `subdomain' method.\n\nIt also allows users to easily modify the URL's query values as a hash.\n  "
  s.email = "flip@x451.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "LICENSE",
    "lib/addressabler.rb",
    "lib/addressabler/query.rb",
    "lib/tlds"
  ]
  s.homepage = "http://github.com/flipsasser/addressabler"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "An Addressable::URI extension adding support for TLDs and query part editing"
  s.test_files = ["spec/addressabler_spec.rb", "spec/spec_helper.rb", "spec/uri_spec.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0"])
      s.add_runtime_dependency(%q<addressable>, [">= 2.2.2"])
    else
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0"])
      s.add_dependency(%q<addressable>, [">= 2.2.2"])
    end
  else
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0"])
    s.add_dependency(%q<addressable>, [">= 2.2.2"])
  end
end

